/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


import * as i0 from '@angular/core';
import * as i1 from './bar-chart.component';
const styles_BarChartComponent:any[] = ([] as any[]);
export const RenderType_BarChartComponent:i0.RendererType2 = i0.ɵcrt({encapsulation:2,
    styles:styles_BarChartComponent,data:{}});
export function View_BarChartComponent_0(_l:any):i0.ɵViewDefinition {
  return i0.ɵvid(0,([] as any[]),(null as any),(null as any));
}
export function View_BarChartComponent_Host_0(_l:any):i0.ɵViewDefinition {
  return i0.ɵvid(0,[(_l()(),i0.ɵeld(0,(null as any),(null as any),1,'bar-chart',([] as any[]),
      (null as any),(null as any),(null as any),View_BarChartComponent_0,RenderType_BarChartComponent)),
      i0.ɵdid(114688,(null as any),0,i1.BarChartComponent,([] as any[]),(null as any),
          (null as any))],(_ck,_v) => {
    _ck(_v,1,0);
  },(null as any));
}
export const BarChartComponentNgFactory:i0.ComponentFactory<i1.BarChartComponent> = i0.ɵccf('bar-chart',
    i1.BarChartComponent,View_BarChartComponent_Host_0,{},{},([] as any[]));
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiQzovVXNlcnMvREVWRUxPUEVSL0RvY3VtZW50cy9KT1NFL0dJVEhVQi9uZy1kMy1jaGFydHMvcGFja2FnZXMvYmFyL3NyYy9iYXItY2hhcnQuY29tcG9uZW50Lm5nZmFjdG9yeS50cyIsInZlcnNpb24iOjMsInNvdXJjZVJvb3QiOiIiLCJzb3VyY2VzIjpbIm5nOi8vL0M6L1VzZXJzL0RFVkVMT1BFUi9Eb2N1bWVudHMvSk9TRS9HSVRIVUIvbmctZDMtY2hhcnRzL3BhY2thZ2VzL2Jhci9zcmMvYmFyLWNoYXJ0LmNvbXBvbmVudC50cyIsIm5nOi8vL0M6L1VzZXJzL0RFVkVMT1BFUi9Eb2N1bWVudHMvSk9TRS9HSVRIVUIvbmctZDMtY2hhcnRzL3BhY2thZ2VzL2Jhci9zcmMvYmFyLWNoYXJ0LmNvbXBvbmVudC50cy5CYXJDaGFydENvbXBvbmVudF9Ib3N0Lmh0bWwiXSwic291cmNlc0NvbnRlbnQiOlsiICIsIjxiYXItY2hhcnQ+PC9iYXItY2hhcnQ+Il0sIm1hcHBpbmdzIjoiQUFBQTs7Ozs7Ozs7Ozs7Ozs7Ozs7b0JDQUE7TUFBQTthQUFBO1VBQUE7SUFBQTs7OzsifQ==
